import React from 'react';

import Link from './Link';

// TODO: require image and base64 it via loader
export default function Favicon() {
    return <Link rel="icon" type="image/x-icon" href="data:;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAW1H6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAQAAAAAAABABEAAAAAABEAEQAAAAAAEQARAAAAAAARABEAAAAAABEAEQAQAA
    EAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQARABEAEQ
    ARABEAEQARABEAEQARABEAEQAAAAAAAAAAC//QAAn/kAAJ/5AACf+QAAn/kAAJvZAACZmQAAmZkA
    AJmZAACZmQAAmZkAAJmZAACZmQAAmZkAAJmZAAD//wAA" />;
}
